# Report month start
START?=	01
# Report month end
STOP?=	03
# Report year
YEAR?=	2024
# Report quarter
QUARTER?=	1

# Entries from the various official and semi-official teams
TeamReports= core.adoc freebsd-foundation.adoc releng.adoc clusteradm.adoc ci.adoc portmgr.adoc

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= audio.adoc bhyve.adoc bsdinstall.adoc

# Changes affecting the base system and programs in it
Userland= libsys.adoc packagekit.adoc

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= wireless.adoc

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= ten64-whle-honeycomb.adoc

# Updating cloud-specific features and bringing in support for new
# cloud platforms
Cloud= azure.adoc cloud-init.adoc openstack.adoc

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation=	doceng.adoc

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= freshports.adoc gcc.adoc valgrind.adoc

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= pot.adoc

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
